# Generated by Django 4.0.4 on 2022-05-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(default='', max_length=250, verbose_name='a phrase or a word')),
                ('translation', models.CharField(default='', max_length=250, verbose_name='translation')),
                ('publish', models.BooleanField(default=False, verbose_name='publish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collocations.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'collocation',
                'verbose_name_plural': 'collocations',
            },
        ),
    ]
